name: Build and deploy Node.js app to Azure Web App - PolyEats

on:
  push:
    branches:
      - TE6
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      - name: npm install, build, and test
        run: |
          npm install --workspaces=false
          npm run -w express-backend build --if-present
          npm run -w express-backend test --if-present
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/express-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: packages/express-backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A44BA0BA1154737B607EEACE00C3DE2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9370C355258C4F449175220A44D2C9A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8A9EE310088A43F58FDC0BC694942DCE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PolyEats'
          slot-name: 'Production'
          package: .
          